# Generated by Django 3.2.13 on 2022-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_text',
            field=models.CharField(default='title', max_length=40),
            preserve_default=False,
        ),
    ]
