# Generated by Django 3.2.13 on 2022-05-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_post_title_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
